# 1. Tomcat Server Setting
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: utf-8

# 2. SpringBoot Environment Setting
spring:
  springdoc:
    #    version: '@project.version@'
    api-docs:
      path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      path: /swagger-ui.html
      disable-swagger-default-url: true
      display-query-params-without-oauth2: true
      doc-expansion: none
  datasource:
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:mysql://127.1.0.1:3306/smdb?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smdb?characterEncoding=utf8
    username: smuser
    password: 111111
#  datasource:
##    url: jdbc:h2:~/tests
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: test
#    password: 1111
#  h2:
#    console:
#      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  output:
    ansi:
      enabled: always

# 4. Logging Setting
logging:
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
  #  error > info > debug

# 5. Application Environment Setting





